### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by Jessejx** [yl305237731/flexible-yolov5#2]
Thanks for your great work. I met this problem when I use resnet as backbone.

Traceback (most recent call last):
  File "train.py", line 527, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 293, in train
    pred = model(imgs)  # forward
  File "/home/jx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jx/Workings/flexible-yolov5-main/od/models/model.py", line 67, in forward
    out = self.backbone(x)
  File "/home/jx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jx/Workings/flexible-yolov5-main/od/models/backbone/resnet.py", line 208, in forward
    x2 = self.layer2(x1)
  File "/home/jx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/jx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jx/Workings/flexible-yolov5-main/od/models/backbone/resnet.py", line 119, in forward
    out = self.conv2(out, offset)
  File "/home/jx/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jx/anaconda3/lib/python3.8/site-packages/torchvision/ops/deform_conv.py", line 143, in forward
    return deform_conv2d(input, offset, self.weight, self.bias, stride=self.stride,
  File "/home/jx/anaconda3/lib/python3.8/site-packages/torchvision/ops/deform_conv.py", line 76, in deform_conv2d
    return torch.ops.torchvision.deform_conv2d(
RuntimeError: expected scalar type Half but found Float

**Comment by yl305237731** [comment]
@Jessejx hi, this problem is caused by resnet with dcn. I have updated the configuration and code set  dcn as False. so, you can use resnet without dcn.  
And I also try to solve this problem so that the network can be trained with DCN,  

`if __name__ == '__main__':
    import torch
    args = {'version': '50', 'dcn': True}
    x = torch.zeros(2, 3, 640, 640).cuda()
    net = resnet(pretrained=False, **args).cuda()
    y = net(x)
    for u in y:
        print(u.shape)

    print(net.out_channels)`
only test  resnet, there is no error, but when i train total network, the error is same as you. And id have check their weights:

weights of DeformConv2d 

![image](https://user-images.githubusercontent.com/9928596/113803092-6de7f380-978e-11eb-8620-37668b591475.png)
weights of norml conv2d

![image](https://user-images.githubusercontent.com/9928596/113803134-80622d00-978e-11eb-9e2c-64a3ef7a54c3.png)

Although they are all float32, we can see that the former should be in half format.  But I don't know why. Therefore, don't use the DCN for now. I will solve it when I have time. thanks!

**Comment by yl305237731** [comment]
I think this is caused by the mixed precision training of apex, and the DCN support for this is not very good. I train resnet with dcn for DBNet, There was no problem. @Jessejx

**Comment by Jessejx** [comment]
> I think this is caused by the mixed precision training of apex, and the DCN support for this is not very good. I train resnet with dcn for DBNet, There was no problem. @Jessejx

Thanks again.

**Comment by yl305237731** [comment]
https://github.com/ultralytics/yolov5/issues/2981

**Comment by ratom** [comment]
I tried to train today, still this issue is not fixed. I also set half=False, still the issue is not fixed. I got this issue while training, not during eval. 
![image](https://user-images.githubusercontent.com/15610639/179381478-57247bc9-994f-4912-86a7-5ebd3acd2d6e.png)

**Comment by ratom** [comment]
Moreover when I complete the training, then it only gave the bounding box but not the corresponding name of the detected object 
![image](https://user-images.githubusercontent.com/15610639/179389822-cd662bf6-7966-4d87-bc45-ee8b5c4ea192.png)

**Comment by Bobo-y** [comment]
@ratom pleasse give me more your configs info, next week i will check it
