### ISSUE TITLE
detector.py应该如何使用？

### ISSUE THREAD

**Issue by OpenCDR** [yl305237731/flexible-yolov5#26]
您好，
  我使用下面的代码来加载训练好的模型：
```
from detector import *

pt_path = 'E:\\flexible-yolov5\\scripts\\best.pt'
img = 'E:\\flexible-yolov5\\source\\00-20.3592.jpg'
class_pth = 'E:\\flexible-yolov5\\source\\classes.txt'

inter = Detector(pt_path=pt_path, namesfile=class_pth, img_size=576,classes=6)
result = inter(img)
print(result)
```
但是出现报错：
```
Traceback (most recent call last):
  File "E:/flexible-yolov5/scripts/detector.py", line 131, in <module>
    inter = Detector(pt_path=pt_path, namesfile=class_pth, img_size=576,classes=6)
  File "E:/flexible-yolov5/scripts/detector.py", line 16, in __init__
    self.model = self.load_model()
  File "E:/flexible-yolov5/scripts/detector.py", line 25, in load_model
    model = attempt_load(self.pt_path, map_location='cpu')  # load FP32 model
  File "E:\flexible-yolov5\od\models\modules\experimental.py", line 118, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "E:\flexible-yolov5\venv\lib\site-packages\torch\serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "E:\flexible-yolov5\venv\lib\site-packages\torch\serialization.py", line 851, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models'
```
我应该如何解决这个问题呢？谢谢。

**Comment by yl305237731** [comment]
@OpenCDR 把你的脚本放到 scripts 下面，然后运行 Python scripts/ 你的脚本.py,  不能直接在scripts 里面跑

**Comment by OpenCDR** [comment]
您好，
这个方法并不管用，还是会报`ModuleNotFoundError: No module named 'models'`。但是官方的detector.py文件是可以使用的。我看了一下sys.path，发现/flexible-yolov5/scripts和/scripts都包含在里边了。

**Comment by yl305237731** [comment]
@你用的官方的pt? 那不行的，只能用这个仓库训练出来的。

**Comment by OpenCDR** [comment]
没有使用官方的pt，使用的是官方的detector.py这个文件

**Comment by yl305237731** [comment]
但我试了一下，可以的呀

**Comment by OpenCDR** [comment]
很奇怪，我怎么着都不行

**Comment by yl305237731** [comment]
由这个报错来看，确实应该是官方代码训练出来的模型，第一层是models, 我这个仓库是od.models

**Comment by OpenCDR** [comment]
那我重新训练一次试试看吧，谢谢您

**Comment by yl305237731** [comment]
客气，训练一个epoch保存一个pt就可以测试了

**Comment by OpenCDR** [comment]
您好，测试过没有问题了。

**Comment by ilem777** [comment]
Hello, I use detector.py to infer a folder image, the specific modification settings are as follows, but the generated image is the same as the original image, there is no detection box, detection object and detection value on the image. How do I need to modify it please?
```
class Detector(object):
    def __init__(self, pt_path, namesfile, img_size, conf_thres=0.25, iou_thres=0.45, classes=5, agnostic_nms=False,
                 xcycwh=True, device=0):    # I have 5 classes, so the classes i change to 5.
```
```
if __name__ == '__main__':

    pt_path = 'runs/train/v5_mobilenet_large/weights/best.pt'                 # the Path to the .pt file
    namesfile = 'configs/classes.txt'                                                           # A txt file with five classes
    model = Detector(pt_path, namesfile, 640, xcycwh=False)
    imgs_root = '../10-test'                                                                         # Path to the folder where the image is detected
    imgs = os.listdir(imgs_root)
    save_dir = 'runs/inference/v5_mobilenet_large'                                   # Path to save images
    if not os.path.exists(save_dir):
        os.mkdir(save_dir)
    for img in imgs:
        im = cv2.imread(os.path.join(imgs_root, img))
        bboxes, scores, ids = model.detect_image(im)
        for idx in range(bboxes.shape[0]):
            bbox = bboxes[idx].astype(int)
            score = scores[idx]
            cv2.rectangle(im, (bbox[0], bbox[1]), (bbox[2], bbox[3]), (0, 0, 255), 2, 1)
        cv2.imwrite(os.path.join(save_dir, img), im)
```

**Comment by ilem777** [comment]
@yl305237731 Um hmm, I changed the classes back to 0, then ran detector.py again, then the test result is still blank.
My classes.txt is as follows, I don't know if there are any errors.
![微信图片编辑_20210527213005](https://user-images.githubusercontent.com/61718945/119834660-bb811100-bf32-11eb-8d8a-ac0bb4aa1980.jpg)
![微信图片_20210527212821](https://user-images.githubusercontent.com/61718945/119834432-8674be80-bf32-11eb-8c17-fb4b3f60bf25.png)

**Comment by yl305237731** [comment]
It has nothing to do with the txt file because it is not used. I have tested it myself, and there is no error, wuwu

**Comment by ilem777** [comment]
If the namesfile is set to None, the code returns an error, tough.
```
if __name__ == '__main__':

    pt_path = 'runs/train/v5_mobilenet_large/weights/best.pt'
    # namesfile = 'configs/classes.txt'
    # model = Detector(pt_path, namesfile, 640, xcycwh=False)
    model = Detector(pt_path, None, 640, xcycwh=False)
    imgs_root = '../10-test'
    imgs = os.listdir(imgs_root)
    save_dir = 'runs/inference/v5_mobilenet_large'
    if not os.path.exists(save_dir):
        os.mkdir(save_dir)
    for img in imgs:
        im = cv2.imread(os.path.join(imgs_root, img))
        bboxes, scores, ids = model.detect_image(im)
        for idx in range(bboxes.shape[0]):
            bbox = bboxes[idx].astype(int)
            score = scores[idx]
            cv2.rectangle(im, (bbox[0], bbox[1]), (bbox[2], bbox[3]), (0, 0, 255), 2, 1)
        cv2.imwrite(os.path.join(save_dir, img), im)
```
```
(venv) F:\PycharmProjects\yolov5_env\flexible-yolov5>python detector.py
Fusing layers...
Traceback (most recent call last):
  File "detector.py", line 130, in <module>
    model = Detector(pt_path, None, 640, xcycwh=False)
  File "detector.py", line 20, in __init__
    self.class_names = self.load_class_names(namesfile)
  File "detector.py", line 27, in load_class_names
    with open(namesfile, 'r', encoding='utf8') as fp:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by yl305237731** [comment]
i will test this on windows today

**Comment by ilem777** [comment]
I am looking forward to your good news.

**Comment by yl305237731** [comment]
wuwu， i am prepare for interview......
