### ISSUE TITLE
How to infer a folder of images?

### ISSUE THREAD

**Issue by ilem777** [yl305237731/flexible-yolov5#27]
Your code is a great job and very rewarding.
But again, I see some differences between your code and authentic yolov5, and I would like to know how to do inference of a batch file (generate inference boxes, inference categories and inference values)?
I see that the original yolov5 has a [detect.py](https://github.com/ultralytics/yolov5/blob/c6b5bfca8592c3426ce0b5f65e559c45d42ff378/detect.py) file, but your codebase does not have it inside.

**Comment by yl305237731** [comment]
in scripts/detector.py, i will update it ， make it more easier to use @ilem777

**Comment by yl305237731** [comment]
@ilem777 hello, please check scripts/detector.py, I already update it.

**Comment by ilem777** [comment]
@yl305237731 Thank you for your very quick reply.
I want to start training, however, I encountered the following error report. How can I solve this problem?
```
(venv) F:\PycharmProjects\yolov5_env\flexible-yolov5>python scripts/train.py  --batch 8 --epochs 200 --data configs/data.yaml --cfg configs/model_resnet.yaml --hyp configs/hyp.scratch.custom2.yaml
Traceback (most recent call last):
  File "scripts/train.py", line 24, in <module>
    from od.models.modules.experimental import attempt_load
  File ".\od\__init__.py", line 1, in <module>
    from .models import Model, ComputeLoss
  File ".\od\models\__init__.py", line 1, in <module>
    from .model import Model
  File ".\od\models\model.py", line 8, in <module>
    from od.models.backbone import build_backbone
  File ".\od\models\backbone\__init__.py", line 5, in <module>
    from .yolov5 import YOLOv5
  File ".\od\models\backbone\yolov5.py", line 3, in <module>
    from utils.general import make_divisible
ModuleNotFoundError: No module named 'utils.general'
```

**Comment by yl305237731** [comment]
There is no problem running under Linux. The simplest solution is copy make_divisible to yolov5.py

**Comment by ilem777** [comment]
Solved, it is the problem of different paths for the two systems.
