### ISSUE TITLE
eval.py的使用问题

### ISSUE THREAD

**Issue by OpenCDR** [yl305237731/flexible-yolov5#30]
您好，我在eval.py中使用了--task speed参数，出现了如下报错：
```Traceback (most recent call last):
  File "eval.py", line 325, in <module>
    test(opt.data, w, opt.batch_size, opt.img_size, 0.25, 0.45, save_json=False, plots=False)
  File "eval.py", line 56, in test
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/xxx/Desktop/flexible-yolov5/od/models/modules/experimental.py", line 118, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "/home/xxx/Softwares/anaconda/envs/welding/lib/python3.8/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/xxx/Softwares/anaconda/envs/welding/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/xxx/Softwares/anaconda/envs/welding/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: '/'
```
val和test参数是没有问题的，请问这是什么原因造成的？

**Comment by yl305237731** [comment]
权重文件路径写错了吧，看报的错应该是写成目录了@OpenCDR
