### ISSUE TITLE
help me ! 

### ISSUE THREAD

**Issue by ONNONS** [yl305237731/flexible-yolov5#31]
thank you for your contribution

Traceback (most recent call last):
  File "/content/flexible-yolov5/scripts/train.py", line 527, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "/content/flexible-yolov5/scripts/train.py", line 77, in train
    ckpt = torch.load(weights, map_location=device)  # load checkpoint
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models'

**Comment by yl305237731** [comment]
@ONNONS Please don't use the official pre training weight in the first training.

**Comment by ONNONS** [comment]
sorry i didn't understand

**Comment by ONNONS** [comment]
!python /content/flexible-yolov5/scripts/train.py --img 416 --batch 16 --epochs 50 --data /content/gdrive/MyDrive/dataset/data.yaml --cfg /content/flexible-yolov5/configs/model_resnet.yaml --name results

**Comment by yl305237731** [comment]
@ONNONS  you should in flexible-yolov5 dir to run python scripts/train.py
