### ISSUE TITLE
关于swin_transformer测试部分的报错解决

### ISSUE THREAD

**Issue by Codingtnl** [yl305237731/flexible-yolov5#34]

**Comment by Codingtnl** [comment]
在测试部分会产生如下错误：
Traceback (most recent call last):
  File "scripts/eval.py", line 318, in <module>
    save_conf=opt.save_conf,
  File "scripts/eval.py", line 86, in test
    model(torch.zeros(1, 3, imgsz, imgsz).to(device).type_as(next(model.parameters())))  # run once
  File "/home/sunyukai/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./od/models/model.py", line 67, in forward
    out = self.backbone(x)
  File "/home/sunyukai/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./od/models/backbone/swin_transformer.py", line 598, in forward
    x_out, H, W, x, Wh, Ww = layer(x, Wh, Ww)
  File "/home/sunyukai/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./od/models/backbone/swin_transformer.py", line 382, in forward
    x = blk(x, attn_mask)
  File "/home/sunyukai/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./od/models/backbone/swin_transformer.py", line 224, in forward
    attn_windows = self.attn(x_windows, mask=attn_mask)  # nW*B, window_size*window_size, C
  File "/home/sunyukai/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./od/models/backbone/swin_transformer.py", line 142, in forward
    x = (attn @ v).transpose(1, 2).reshape(B_, N, C)
RuntimeError: Expected object of scalar type Float but got scalar type Half for argument #2 'mat2' in call to _th_bmm_out

我查看参数之后发现是attn部分受到mask的影响数据类型从float16变成了float32，我个人的解决办法是
x = (attn @ v).transpose(1, 2).reshape(B_, N, C)
变成了
x = (attn.type_as(v) @ v).transpose(1, 2).reshape(B_, N, C)
目前可以成功eval，分享一下，期待能收获更好的解决办法

**Comment by yl305237731** [comment]
@Codingtnl 按照默认脚本测试会采用半精度我估计哈swin 实现上半精度可能有问题，关掉后就没问题了。按照你的方法把他们强制转换成同样类型也可以。

**Comment by Codingtnl** [comment]
> @Codingtnl 按照默认脚本测试会采用半精度我估计哈swin 实现上半精度可能有问题，关掉后就没问题了。按照你的方法把他们强制转换成同样类型也可以。

对了想问一下如果我要加载官方的swin预训练模型我该怎么做比较好呢，自己训swin收敛的有点慢

**Comment by yl305237731** [comment]
@Codingtnl 我参照的原始仓库里有加载权重的代码，但我没试过呢，不知道直接加上会不会报错

**Comment by zxm111222333** [comment]
> > @Codingtnl 按照默认脚本测试会采用半精度我估计哈swin 实现上半精度可能有问题，关掉后就没问题了。按照你的方法把他们强制转换成同样类型也可以。
> 
> 对了想问一下如果我要加载官方的swin预训练模型我该怎么做比较好呢，自己训swin收敛的有点慢

想问老哥有办法加载预训练模型了吗？

**Comment by yssid** [comment]
Thanks @yl305237731 let me try to change with x = (attn.type_as(v) @ v).transpose(1, 2).reshape(B_, N, C)
Let's see ... and Thanks for the Quick reply.

**Comment by wch243294382** [comment]
> 

请问能加载了吗

**Comment by Bobo-y** [comment]
> > 
> 
> 请问能加载了吗

add  pretrained:True in  backbone of  model_swin.yaml 
`
backbone:
  type: swin
  version: tiny # tiny small base  large
  pretrained: True
`
