### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'tell'

### ISSUE THREAD

**Issue by HHaa-gif** [yl305237731/flexible-yolov5#36]
Hello
In the process of reproducing your code, I encountered the following problem：
Traceback (most recent call last):
  File "scripts/train.py", line 527, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "scripts/train.py", line 189, in train
    image_weights=opt.image_weights, quad=opt.quad, prefix=colorstr('train: '))
  File "/home/lab/liyuping/flexible-yolov5-main/flexible-yolov5-main/od/data/datasets.py", line 71, in create_dataloader
    prefix=prefix)
  File "/home/lab/liyuping/flexible-yolov5-main/flexible-yolov5-main/od/data/datasets.py", line 377, in __init__
    cache, exists = torch.load(cache_path), True  # load
  File "/home/lab/anaconda3/envs/yolo/lib/python3.7/site-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/home/lab/anaconda3/envs/yolo/lib/python3.7/site-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
AttributeError: 'PosixPath' object has no attribute 'tell'

Do you know how to solve it？Look forward to your reply.
Thanks

**Comment by yl305237731** [comment]
sorry, i never mett this error.
